---

- name: Set Hostname
  hostname: name="{{ inventory_hostname }}"

- name: Disable AWS cloud hostname. Ok to fail
  ignore_errors: yes
  lineinfile: "dest=/etc/cloud/cloud.cfg
              line='preserve_hostname: true'
              state=present"

- name: Ensure that system is up to-date
  yum: name=* state=latest

- name: Install packages for happy life
  package:
    name:
      - python3-libselinux
      - mc
      - epel-release
      - bind-utils
      - telnet
      - firewalld
      - chrony

- name: Install additional packages for happy life
  package:
    name:
      - screen

- name: Switch SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Set firewalld is enabled
  service: name=firewalld enabled=yes

- name: Enable ssh in firewalld
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
  
- name: Disable cockpit in firewalld
  firewalld:
    service: cockpit
    permanent: yes
    zone: public
    state: disabled

- name: Set firewalld to be started
  service: name=firewalld state=started

- name: Set chrony is enabled
  service: name=chronyd enabled=yes
  
- name: Set chrony to be started
  service: name=chronyd state=started

- name: Enforce time sync first step
  shell: "chronyc -a 'burst 4/4'"
  
- name: Enforce time sync second step
  shell: "chronyc -a makestep"
  
